version: "3.8"

services:
  flask_app:
    build: .
    volumes:
      - ./archive:/app/archive
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database  # ensures that the mongodb dataabse starts before the flask app
    networks:
      - app-network

  database:
    image: "mongo:latest"
    container_name: database
    ports:
      - "27017:27017" 
    networks:
      - app-network

networks:
  app-network:
