version: "3.8"

services:
  flask_app:
    build: .
    volumes:
      - ./archive:/app/archive
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - database  # ensures that the mongodb dataabse starts before the flask app
    networks:
      - app-network
  

  database:
    image: "mongo:latest"
    container_name: database
    ports:
      - "27017:27017" 
    networks:
      - app-network
  
  data_processor:
    build: .
    volumes:
      - ./archive:/app/archive  # Ensure it has access to the CSV file
    depends_on:
      - database
    command: ["python", "-m", "src.ratings_processor"]
    env_file:
      - .env
    restart: on-failure  # Restart if it fails due to MongoDB not being ready
    networks:
      - app-network  # Make sure it's on the same network as MongoDB

networks:
  app-network:
