HTTP_STATUS_CODE_OK = 200
HTTP_STATUS_CODE_CREATED = 200
HTTP_STATUS_CODE_BAD_REQUEST = 400
HTTP_STATUS_CODE_NOT_FOUND = 404
HTTP_STATUS_CODE_CONFLICT = 409
HTTP_STATUS_CODE_INTERNAL_SERVER_ERROR = 500